"""Added Column

Revision ID: 1f1548e40218
Revises: 
Create Date: 2025-04-13 17:34:34.345271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1548e40218'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cred', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transportid', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cred', schema=None) as batch_op:
        batch_op.drop_column('transportid')

    # ### end Alembic commands ###
